### PR TITLE
opam packages for examples, use Dune for opam ci, add Nix ci

### PR DESCRIPTION
**Pull request by palmskog**
Dune is much more flexible for opam-based CI. To test regular make builds in CI, we use Nix.

### CODE REVIEW

**Comment by RalfJung** [comment]
This seems to not just use Dune for CI, but generally for all opam-based installs? The makefile is not tested at all any more, is it better to remove it then?

I am okay landing this, but I am also entirely unfamiliar with Dune and nix and a bunch of other things you are using here. But if you want to keep maintaining this, @palmskog, that's good enough for me.

**Comment by palmskog** [comment]
@RalfJung the main reason I use Dune for CI is that it would take quite a lot of Makefile hacking to make the examples build and install in isolation (without having to rebuild autosubst itself multiple times). Just adding the `dune` scripts means I can leave the makefiles alone.

I actually do test the regular autosubst makefile build through Nix, the output here shows that `make` and `make install` are being invoked:  https://github.com/coq-community/autosubst/runs/1581105386?check_suite_focus=true#step:5:357

The only non-standard (non-templated) part of the setup is the incremental Docker-based CI, that in turn builds all three opam packages. So I wouldn't expect a lot of CI maintenance going forward except for testing new Coq and SSReflect versions.

**Comment by RalfJung** [comment]
So opam uses Dune but Nix uses make directly? That also seems like a strange setup, doesn't it?

Ideally we'd have just one build system, I feel.^^

**Comment by palmskog** [comment]
I used Dune in the opam packages for the Docker-based CI so I could sidestep all the problems in the old and near-unusable makefiles. The goal here is to enable simple testing in isolation of all the examples for a single Coq version in the Docker CI. Using makefiles is the standard way to build packages in Nix. We have used a combination of opam and Nix in many projects, and it has worked out fine.

I'm sure the ideal is to have a single build system and script, but essentially we are working with legacy tooling in a majority of Coq projects right now, and I believe full testing in CI is more important than build uniformity.

**Comment by RalfJung** [comment]
Well, but we can have full testing in CI with just makefiles. I'd say that describes the situation on master without this PR.

I get the motivation for dune, but only if it can *replace* the makefile. Otherwise it seems more like [this XKCD](https://xkcd.com/927/).

**Comment by palmskog** [comment]
Without significant refactoring the current Makefiles, you can't have fully separated builds of the examples. The current makefiles require that the main autosubst `.vo` files *in the repo* are the ones used by the examples. You can't have, for example, the ssr examples use an already-installed autosubst library.

If you look at the diff closely, you can also see that using an already-installed autosubst for the ssr examples was actually impossible before (regardless of makefiles) due to having 
```coq
Require Import Autosubst.
```
instead of the correct 
```coq
Require Import Autosubst.Autosubst.
```

**Comment by RalfJung** [comment]
> you can't have fully separated builds of the examples.

But why would you want that?

> If you look at the diff closely, you can also see that using an already-installed autosubst for the ssr examples was actually impossible before (regardless of makefiles) due to having

That seems like a bug that one can fix. Using `-Q` instead of `-R` would be better anyway.

**Comment by palmskog** [comment]
So you're saying you *do not want* users to be able to install and depend on autosubst and its examples separately from each other? To me, this is like saying users should not be able to install `mathcomp-algebra` and `mathcomp-solvable` separately, but should always get the full mathcomp, or only ssreflect.

**Comment by RalfJung** [comment]
I don't think the examples should ever be installed. They are examples, so basically documentation. They are not designed to be things that one can import or so, they are designed to be copy-pasted and adjusted. That is my interpretation anyway.

**Comment by palmskog** [comment]
I disagree that the examples are not something anyone would want to install - in particular many of the Ssreflect example files are generally useful:
- https://github.com/coq-community/autosubst/blob/master/examples/ssr/AutosubstSsr.v - general instantiation of ssreflect functions for Autosubst
- https://github.com/coq-community/autosubst/blob/master/examples/ssr/ARS.v - general lemmas for working with small-step reduction relations.

**Comment by RalfJung** [comment]
I think if these are things one might want to install, they should not be called "examples". If parts of these examples are generally useful, they should be moved to the main library (or an autosubst-ssr library) so it becomes clear that these are "public API" that shouldn't be changed lightly.

**Comment by Zimmi48** [comment]
> I think if these are things one might want to install, they should not be called "examples". If parts of these examples are generally useful, they should be moved to the main library (or an autosubst-ssr library) so it becomes clear that these are "public API" that shouldn't be changed lightly.

I would tend to agree with this, though it wasn't done so far. So, if the conclusion was to close this PR, I suggest hitting the close button. Otherwise, this PR needs to be updated, because it is not up-to-date with the latest Nix CI templates.

**Comment by RalfJung** [comment]
> I would tend to agree with this, though it wasn't done so far. 

I think the current makefile does not install the examples. So what "wasn't done"?

**Comment by Zimmi48** [comment]
To move interesting files to the `autosubst` package or a new `autosubst-ssr` one.

**Comment by RalfJung** [comment]
Yeah, I think files that users want to depend on should be moved from "examples" to a more aptly named place. I don't have a clear idea which of the examples could be useful as libraries, but when someone shows up and says they want to import one of these files that sounds like clear sign. :D

But I don't think we should do this for all examples without further consideration. So I'll close this PR for now, but I'll happily pick this up again in the future if someone wants to work on it again. :)

**Comment by palmskog** [comment]
It's disappointing that this PR that focused improving CI and testing of the project was left in limbo and then closed after some random interval, in essence for not completely refactoring a large chunk of the project. We use opam packages for testing reasons all the time in the general Coq community. I think the chance that someone else will pick up something similar in the near future is vanishingly small.

**Comment by RalfJung** [comment]
@palmskog I'm sorry to have disappointed; the PR was left in a limbo after my last comment so I figured you had lost interest. If you are still interested I am happy to continue the discussion.

The reason I objected to the PR is that it *does* perform a major refactoring, namely installing the "examples" files. I view this as a rather large change to the "public API surface" of this project. If it had just updated the CI it would have been a no-brainer!

**Comment by palmskog** [comment]
The way we run/test any file(s) is by installing them, that's just how opam and Nix works for Coq. There is no feasible way to avoid that, in my view. The content of the core autosubst package was completely unchanged. Also, anyone who runs the examples will currently have them placed in the inappropriate `Ssr` namespace, which was something else I fixed in this PR.

If you want to revive the PR, that's fine by me, and I can review a revived PR from a Coq automation standpoint, but I don't think this discussion is going to go anywhere productive.

**Comment by RalfJung** [comment]
> The way we run/test any file(s) is by installing them, that's just how opam and Nix works for Coq. 

In Iris we have an opam package that contains files that are built to be tested but not installed. It's totally possible to do that.

But I guess the shared infrastructure you are using here does not support this, so we have to work around that limitation by adding a new opam package. We could however possibly still make the `install` step of that opam package a NOP? Or if that is not possible, make it clear in the description that this package is not meant to ever be imported anywhere and is just an internal implementation detail of autosubst CI?

**Comment by palmskog** [comment]
Our idiom is to completely delegate the details of whether or not a package will be installed (and where) to Dune. If you look in the proposed opam packages, they only have a `build` clause and no `install` clause. Emilio is also working towards completely compositional builds of the whole Coq universe (duniverse), where it won't matter whether something resides in `user-contribs` or not. Hence, the only feasible long-term configuration option is probably to put a disclaimer ("DO NOT INSTALL") in the opam package `synopsis`. But this seems pretty redundant to me, since almost nobody installs random package definitions in Coq project repositories - they either use the default `make && make install` or install via the Coq opam archive.

**Comment by RalfJung** [comment]
> If you look in the proposed opam packages, they only have a build clause and no install clause

According to [the docs](https://opam.ocaml.org/doc/Packaging.html#The-file-format-in-more-detail), dune just uses a different approach to install files:

> This field can be skipped if your package generates a <pkgname>.install file, like is the case when using dune.

I don't quite understand why a "compositional build" would be unable to have build steps that do not correspond to install steps (that seems like a fairly fundamental feature of any package manager to me, and also entirely orthogonal to `user-contribs` concerns)... but I also don't think this matters very much for this discussion. This is a digression.

---

All I want to ensure is that nobody thinks that these "examples" packages (which exist solely to fit into the limitations of the shared CI infrastructure) can be imported and be expected to keep working in future versions of autosubst. You now make it sound like nobody would expect that from the mere existence of an autosubst examples opam file in this repo, but you also said yourself last year (further up this thread) that you actually wanted to import those examples -- so back then it very much looked like you were arguing *for* making those files installable.

My [other concern](https://github.com/coq-community/autosubst/pull/23#issuecomment-748495828) with this PR is that it adds a 2nd build system without removing the old one -- I'd rather not maintain both a dune-based and a makefile-based build system.

The first issue can be solved with appropriate package descriptions, if there is no technical solution. For the second issue, I don't know what it takes to avoid having 2 build systems.

**Comment by Zimmi48** [comment]
>The first issue can be solved with appropriate package descriptions, if there is no technical solution. For the second issue, I don't know what it takes to avoid having 2 build systems.

The main problem with not keeping the legacy build system around is that Dune doesn't yet properly offer editor support, so you have to end up using a hackish `_CoqProject` to work around that. But there is no fundamental reason beyond that AFAICT.

**Pull request closed without merging**
