### PR TITLE
Remove all uses of omega from example-plain. Use lia instead.

### PR DESCRIPTION
**Pull request by Zimmi48**
Restore compatibility with Coq 8.14 and master.

### CODE REVIEW

**Comment by Zimmi48** [comment]
The CI results seem to indicate that this update requires dropping compatibility with Coq 8.10. @RalfJung @co-dan no opposition to that?

**Comment by RalfJung** [comment]
I am fine with making Coq 8.11 the minimum supported version.

**Comment by Zimmi48** [comment]
Updated to drop support for Coq 8.10. I've also regenerated various files from the templates. If you do not like the changes to the README, I can revert them.

**Comment by RalfJung** [comment]
LGTM!

I'll just go ahead an merge this; if someone really still needs 8.10 they can just use an older commit.

**Comment by co-dan** [comment]
Thanks! Removing the old mentions of omega is good.

**Comment by Zimmi48** [comment]
> I'll just go ahead an merge this; if someone really still needs 8.10 they can just use an older commit.

Or the latest release :)

**Pull request merged**
